name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Sanity check: versions + import + tiny run
      - name: Sanity check (import + tiny run)
        env:
          MPLBACKEND: Agg
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import sys, platform
          print("Python:", sys.version)
          print("Platform:", platform.platform())
          import numpy as np, pandas as pd, matplotlib
          print("numpy:", np.__version__, "pandas:", pd.__version__, "matplotlib:", matplotlib.__version__)
          from src.zeta_calculator import NSConfig, run_simulation
          print("Import OK. Running tiny simulation…")
          cfg = NSConfig(N=16, steps=2, dt=0.01, nu=0.01, save_every=1)
          out = run_simulation("taylor_green", cfg)
          print("Tiny run OK. Keys:", sorted(out.keys()))
          PY

      - name: Run tests (pytest)
        env:
          MPLBACKEND: Agg
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -vv
